apiVersion: v2
appVersion: 1.31.0-alpha.80f4dd6b14b62a35cb3fd79bda665b675288239e
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.80f4dd6b14b62a35cb3fd79bda665b675288239e
