apiVersion: v2
appVersion: 1.32.0-alpha.b32dee014b25ade888321657a30b38162d7aee1a
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.b32dee014b25ade888321657a30b38162d7aee1a
