apiVersion: v2
appVersion: 1.31.0-alpha.252c10eb18997c7e5951d75b5b6bdd62c69d0f1c
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- istiod
- istio-discovery
name: istiod
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.252c10eb18997c7e5951d75b5b6bdd62c69d0f1c
