apiVersion: v2
appVersion: 1.28-alpha.3326a70440e623ab88d8f4d928ad9f26d2d1dfd9
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.28-alpha.3326a70440e623ab88d8f4d928ad9f26d2d1dfd9
