apiVersion: v2
appVersion: 1.32.0-alpha.f199e14029c2831975a98c3032561742b6061d2c
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

