apiVersion: v2
appVersion: 1.31.0-alpha.8dbc3a3daae51f4c566840a40d602330932009be
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

