apiVersion: v2
appVersion: 1.31.0-alpha.58e9892e6a60d635c1f661c95f0004f52867b379
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

