apiVersion: v2
appVersion: 1.31.0-alpha.80f4dd6b14b62a35cb3fd79bda665b675288239e
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

