apiVersion: v2
appVersion: 1.30-alpha.d9ada8aa419ebc88620a6087ae56383768a1eb2c
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.30-alpha.d9ada8aa419ebc88620a6087ae56383768a1eb2c
