#syntax=docker/dockerfile:1.12

FROM build-harbor.alauda.cn/mlops/static@sha256:d2185a95c5e553a32e4f82d8138ccb78b57242f987985bd089ae2fb3c21e18d0

ARG TARGETOS TARGETARCH

COPY --link out/${TARGETOS}_${TARGETARCH}/sail-operator /sail-operator
COPY --link resources /var/lib/sail-operator/resources

USER 697:697
WORKDIR /
ENTRYPOINT ["/sail-operator"]
