apiVersion: v2
appVersion: 1.25-alpha.ce8d16b3f54a2e3cde56dab87a98aac4004956d1
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.25-alpha.ce8d16b3f54a2e3cde56dab87a98aac4004956d1
