apiVersion: v2
appVersion: 1.31.0-alpha.f48d1ae88afbf4de98afa2b8567fa16ab2072c01
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

