apiVersion: v2
appVersion: 1.31.0-alpha.036c5eac5789e0c5585c76c14994bbe449335ab2
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

