apiVersion: v2
appVersion: 1.31.0-alpha.2e4387a00e7f14c9364ab06f38ce80bb4f975e28
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

