apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: sailoperator
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: sailoperator
    app.kubernetes.io/part-of: sailoperator
    release: prometheus
  name: sailoperator-metrics-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: sail-operator-metrics-service.openshift-operators.svc
  selector:
    matchLabels:
      control-plane: sail-operator
