apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: sailoperator-prometheus-rolebinding
    app.kubernetes.io/name: clusterrolebinding
  name: sailoperator-prometheus-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sailoperator-role
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
- kind: ServiceAccount
  name: prometheus-user-workload
  namespace: openshift-user-workload-monitoring
