apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: sailoperator
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: sailoperator
    app.kubernetes.io/part-of: sailoperator
    release: prometheus
  name: sailoperator-metrics-recording-rules
spec:
  groups:
  - interval: 30s
    name: sailoperator.istiod.rules
    rules:
    - expr: sum(sailoperator_istiod_total) by (app.kubernetes.io/version)
      record: sailoperator_istiod_total
  - interval: 30s
    name: sailoperator.ztunnel.rules
    rules:
    - expr: sum(sailoperator_ztunnel_total) by (app.kubernetes.io/version)
      record: sailoperator_ztunnel_total
