apiVersion: v2
appVersion: 1.31-alpha.3f6f77b340749825366196dfd6b116d8a2e207c1
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

