apiVersion: v2
appVersion: 1.31-alpha.67febb6d28c3b46b6441bf6cba2bb381a06cd62f
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.31-alpha.67febb6d28c3b46b6441bf6cba2bb381a06cd62f
