apiVersion: v2
appVersion: 1.31.0-alpha.c1848c8a6ebde02f90c421be08c359d32fcd66eb
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.c1848c8a6ebde02f90c421be08c359d32fcd66eb
