annotations:
  org.opencontainers.image.ref.name: refs/tags/1.28.3-asm-r3
  org.opencontainers.image.revision: b4bf499d97b4c6284824d83b637b04ad8b3d298c
  org.opencontainers.image.source: https://github.com/alauda-mesh/istio
apiVersion: v2
appVersion: 1.28.3-asm-r3
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.28.3-asm-r3
