apiVersion: v2
appVersion: 1.32.0-alpha.c006a081a582c4812421ee6bcd77097c6b909d4b
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

