apiVersion: v2
appVersion: 1.30-alpha.2fb82507f44514c7709fafe5e54c85a4755f3e9f
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

