apiVersion: v2
appVersion: 1.31.0-alpha.0f5c0b282cb71e420ca204a5c5758285d47ed388
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.0f5c0b282cb71e420ca204a5c5758285d47ed388
