apiVersion: v2
appVersion: 1.31.0-alpha.c1a23dd755587008530f7138a1db443a2ccc8f25
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.c1a23dd755587008530f7138a1db443a2ccc8f25
