apiVersion: v2
appVersion: 1.30-alpha.3e42231932825f8b57844ed3313ec5bce3402397
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

