apiVersion: v2
appVersion: 1.32.0-alpha.e1888d9ac78cf33b410984f1b2e4c1f9d2a7e86d
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.e1888d9ac78cf33b410984f1b2e4c1f9d2a7e86d
