apiVersion: v2
appVersion: 1.31-alpha.4cc49d2e76c2cd55d5a68e414570fdd074c11241
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- istiod
- istio-discovery
name: istiod
sources:
- https://github.com/istio/istio
version: 1.31-alpha.4cc49d2e76c2cd55d5a68e414570fdd074c11241
