apiVersion: v2
appVersion: 1.31.0-alpha.c16f17382ea2d3bec9225829c3f0acfa17d44d6b
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

