apiVersion: v2
appVersion: 1.31.0-alpha.7c8cb4d3edc7c5027176b5dcb1da358a8df5927c
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.7c8cb4d3edc7c5027176b5dcb1da358a8df5927c
