apiVersion: v2
appVersion: 1.32.0-alpha.785bf23f433c54f2d5759dbd1f5b6a6161665914
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

