apiVersion: v2
appVersion: 1.30-alpha.222ea3cc6c86b04d0e6285a9c5e62156e8569889
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.30-alpha.222ea3cc6c86b04d0e6285a9c5e62156e8569889
