annotations:
  org.opencontainers.image.ref.name: refs/tags/1.28.3-asm-r4
  org.opencontainers.image.revision: 210dfc43fd631f476ebb63874f80cb3f4a065c46
  org.opencontainers.image.source: https://github.com/alauda-mesh/istio
apiVersion: v2
appVersion: 1.28.3-asm-r4
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.28.3-asm-r4
