apiVersion: v2
appVersion: 1.31.0-alpha.c3a9d27567bc713c7ef38ef9f9a29f88415dfa25
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.c3a9d27567bc713c7ef38ef9f9a29f88415dfa25
