apiVersion: v2
appVersion: 1.31.0-alpha.ddc812f7772e9c9a25a3a53d146b1ccb21d1ed27
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

