// Variables embedded for GitHub compatibility
:istio_latest_version: 1.28.1
:istio_latest_version_revision_format: 1-28-1
:istio_latest_tag: v1.28-latest
:istio_release_name: release-1.28
:istio_latest_minus_one_version: 1.28.0
:istio_latest_minus_one_version_revision_format: 1-28-0

link:../README.adoc[Return to Project Root]

== Getting Started

== Table of Contents

* <<getting-started,Getting Started>>
** <<installation-on-openshift,Installation on OpenShift>>
*** <<installing-through-the-web-console,Installing through the web console>>
*** <<installing-using-the-cli,Installing using the CLI>>
** <<installation-from-source,Installation from Source>>
** <<migrating-from-istio-in-cluster-operator,Migrating from Istio in-cluster Operator>>
*** <<converter-script-to-migrate-istio-in-cluster-operator-configuration-to-sail-operator,Converter Script to Migrate Istio in-cluster Operator Configuration to Sail Operator>>
**** <<usage,Usage>>
**** <<sample-command-only-with-input-file,Sample command only with input file>>
**** <<sample-command-with-custom-output-namespace-and-version,Sample command with custom output, namespace, and version>>
** <<uninstalling,Uninstalling>>
*** <<deleting-istio,Deleting Istio>>
*** <<deleting-istiocni,Deleting IstioCNI>>
*** <<deleting-the-sail-operator,Deleting the Sail Operator>>
*** <<deleting-the-istio-system-and-istio-cni-projects,Deleting the istio-system and istio-cni Projects>>
*** <<decide-whether-you-want-to-delete-the-crds-as-well,Decide whether you want to delete the CRDs as well>>

[[getting-started]]

[[installation-on-openshift]]
== Installation on OpenShift

[[installing-through-the-web-console]]
=== Installing through the web console

1. In the OpenShift Console, navigate to the OperatorHub by clicking **Operator** -> **Operator Hub** in the left side-pane.

2. Search for "sail".

3. Locate the Sail Operator, and click to select it.

4. When the prompt that discusses the community operator appears, click **Continue**, then click **Install**.

5. Use the default installation settings presented, and click **Install** to continue.

6. Click **Operators** -> **Installed Operators** to verify that the Sail Operator 
is installed. `Succeeded` should appear in the **Status** column.

[[installing-using-the-cli]]
=== Installing using the CLI

*Prerequisites*

* You have access to the cluster as a user with the `cluster-admin` cluster role.

*Steps*

1. Create the `openshift-operators` namespace (if it does not already exist).

    [source,bash,subs="attributes+"]
    ----
    kubectl create namespace openshift-operators
    ----

2. Create the `Subscription` object with the desired `spec.channel`.

   [source,bash,subs="attributes+"]
   ----
   kubectl apply -f - <<EOF
       apiVersion: operators.coreos.com/v1alpha1
       kind: Subscription
       metadata:
         name: sailoperator
         namespace: openshift-operators
       spec:
         channel: "0.1-nightly"
         installPlanApproval: Automatic
         name: sailoperator
         source: community-operators
         sourceNamespace: openshift-marketplace
   EOF
   ----

3. Verify that the installation succeeded by inspecting the CSV status.

    [source,console,subs="attributes+"]
    ----
    kubectl get csv -n openshift-operators
    NAME                                     DISPLAY         VERSION                    REPLACES                                 PHASE
    sailoperator.v0.1.0-nightly-2024-06-25   Sail Operator   0.1.0-nightly-2024-06-25   sailoperator.v0.1.0-nightly-2024-06-21   Succeeded
    ----

    `Succeeded` should appear in the sailoperator CSV `PHASE` column.

[[installation-from-source]]
== Installation from Source

If you're not using OpenShift or simply want to install from source, follow the link:../README.adoc#deploying-the-operator[instructions in the Contributor Documentation].

[[migrating-from-istio-in-cluster-operator]]
== Migrating from Istio in-cluster Operator

If you're planning to migrate from the link:https://istio.io/latest/blog/2024/in-cluster-operator-deprecation-announcement/[now-deprecated Istio in-cluster operator] to the Sail Operator, you will have to make some adjustments to your Kubernetes Resources. While direct usage of the IstioOperator resource is not possible with the Sail Operator, you can very easily transfer all your settings to the respective Sail Operator APIs. As shown in the link:../README.adoc#concepts[Concepts] section, every API resource has a `spec.values` field which accepts the same input as the `IstioOperator`'s `spec.values` field. Additionally, the link:../README.adoc#istio-resource[Istio resource] provides a field for mesh configuration that accepts the same input as IstioOperator's `spec.meshConfig` field, though it is now located under spec.values (i.e., at spec.values.meshConfig).

Another important distinction between the two operators is that Sail Operator can manage and install different versions of Istio and its components, whereas the in-cluster operator always installs the version of Istio that it was released with. This makes managing control plane upgrades much easier, as the operator update is disconnected from the control plane update.

So for a simple Istio deployment, the transition will be very easy:

[source,yaml]
----
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    pilot:
      traceSampling: 0.1
----

becomes

[source,yaml]
----
apiVersion: sailoperator.io/v1
kind: Istio
spec:
  values:
    meshConfig:
      accessLogFile: /dev/stdout
    pilot:
      traceSampling: 0.1
  version: v{istio_latest_version}
----

Note that the only field that was added is the `spec.version` field. There are a few situations however where the APIs are different and require different approaches to achieve the same outcome.

=== Setting environments variables for Istiod

In Sail Operator, all `.env` fields are `map[string]string` instead of `struct{}`, so you have to be careful with values such as `true` or `false` - they need to be in quotes in order to pass the type checks!

That means the following YAML

[source,yaml]
----
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default
spec:
  values:
    global:
      istiod:
        enableAnalysis: true
    pilot:
      env:
        PILOT_ENABLE_STATUS: true
----

becomes

[source,yaml]
----
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  values:
    global:
      istiod:
        enableAnalysis: true
    pilot:
      env:
        PILOT_ENABLE_STATUS: "true"
  version: v{istio_latest_version}
  namespace: istio-system
----

Note the quotes around the value of `spec.values.pilot.env.PILOT_ENABLE_STATUS`. Without them, Kubernetes would reject the YAML as it expects a value of type `string` but receives a `boolean`.

=== Components field

Sail Operator's Istio resource does not have a `spec.components` field. Instead, you can enable and disable components directly by setting `spec.values.<component>.enabled: true/false`. Other functionality exposed through `spec.components` like the k8s overlays is not currently available.

=== CNI lifecycle management

The CNI plugin's lifecycle is managed separately from the control plane. You will have to create a link:../README.adoc#istiocni-resource[IstioCNI resource] to use CNI.

[[converter-script-to-migrate-istio-in-cluster-operator-configuration-to-sail-operator]]
=== Converter Script to Migrate Istio in-cluster Operator Configuration to Sail Operator

This script is used to convert an Istio in-cluster operator configuration to a Sail Operator configuration. Upon execution, the script takes an input YAML file and istio version and generates a sail operator configuration file.

[[usage]]
==== Usage
To run the configuration-converter.sh script, you need to provide four arguments, only input file is required other arguments are optional:

1. Input file path (<input>): The path to your Istio operator configuration YAML file (required).
2. Output file path (<output>): The path where the converted Sail configuration will be saved. If not provided, the script will save the output with -sail.yaml appended to the input file name.
3. Namespace (-n <namespace>): The Kubernetes namespace for the Istio deployment. Defaults to istio-system if not provided.
4. Version (-v <version>): The version of Istio to be used. If not provided, the `spec.version` field will be omitted from the output file and the operator will deploy the latest version when the YAML manifest is applied.

[source,bash,subs="attributes+"]
----
./tools/configuration-converter.sh </path/to/input.yaml> [/path/to/output.yaml] [-n namespace] [-v version]
----

[[sample-command-only-with-input-file]]
===== Sample command only with input file:

[source,bash,subs="attributes+"]
----
./tools/configuration-converter.sh /home/user/istio_config.yaml
----

[[sample-command-with-custom-output-namespace-and-version]]
===== Sample command with custom output, namespace, and version:

[source,bash,subs="attributes+"]
----
./tools/configuration-converter.sh /home/user/input/istio_config.yaml /home/user/output/output.yaml -n custom-namespace -v v{istio_latest_version}
----

[WARNING]
====
This script is still under development.
Please verify the resulting configuration carefully after conversion to ensure it meets your expectations and requirements.
====

[[uninstalling]]
== Uninstalling

[[deleting-istio]]
=== Deleting Istio
1. In the OpenShift Container Platform web console, click **Operators** -> **Installed Operators**.
2. Click **Istio** in the **Provided APIs** column.
3. Click the Options menu, and select **Delete Istio**.
4. At the prompt to confirm the action, click **Delete**.

[[deleting-istiocni]]
=== Deleting IstioCNI
1. In the OpenShift Container Platform web console, click **Operators** -> **Installed Operators**.
2. Click **IstioCNI** in the **Provided APIs** column.
3. Click the Options menu, and select **Delete IstioCNI**.
4. At the prompt to confirm the action, click **Delete**.

[[deleting-the-sail-operator]]
=== Deleting the Sail Operator
1. In the OpenShift Container Platform web console, click **Operators** -> **Installed Operators**.
2. Locate the Sail Operator. Click the Options menu, and select **Uninstall Operator**.
3. At the prompt to confirm the action, click **Uninstall**.

[[deleting-the-istio-system-and-istio-cni-projects]]
=== Deleting the istio-system and istio-cni Projects
1. In the OpenShift Container Platform web console, click  **Home** -> **Projects**.
2. Locate the name of the project and click the Options menu.
3. Click **Delete Project**.
4. At the prompt to confirm the action, enter the name of the project.
5. Click **Delete**.

[[decide-whether-you-want-to-delete-the-crds-as-well]]
=== Decide whether you want to delete the CRDs as well
OLM leaves this link:https://olm.operatorframework.io/docs/tasks/uninstall-operator/#step-4-deciding-whether-or-not-to-delete-the-crds-and-apiservices[decision] to the users.
If you want to delete the Istio CRDs, you can use the following command.

[source,bash,subs="attributes+"]
----
kubectl get crds -oname | grep istio.io | xargs kubectl delete
----
