annotations:
  org.opencontainers.image.ref.name: refs/tags/1.28.1-asm-r5
  org.opencontainers.image.revision: bd91c79c5fda893e761a33c54e5dc8e1e038cf4e
  org.opencontainers.image.source: https://github.com/alauda-mesh/istio
apiVersion: v2
appVersion: 1.28.1-asm-r5
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.28.1-asm-r5
