apiVersion: v2
appVersion: 1.32.0-alpha.10863c4d008fa620273a0cd281407f92091ad12d
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

