# Deprecated. Use the "remote" profile instead.
apiVersion: sail-operator.io/v1alpha1
kind: Istio
spec:
  values:
    global:
      externalIstiod: true
      omitSidecarInjectorConfigMap: true
      configCluster: false
    pilot:
      configMap: false
    telemetry:
      enabled: false
