apiVersion: v2
appVersion: 1.31.0-alpha.bd309b9694ffa3ff26ac0c322745bfee9e13ea2f
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.bd309b9694ffa3ff26ac0c322745bfee9e13ea2f
