apiVersion: v2
appVersion: 1.30-alpha.c524abf09e44ad28cae388a652310070f19f9ac6
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.30-alpha.c524abf09e44ad28cae388a652310070f19f9ac6
