apiVersion: v2
appVersion: 1.30-alpha.6fd4e792817ad3b246f2e0c378c3976b722536ce
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

