apiVersion: v2
appVersion: 1.32.0-alpha.b9027949a11ef01c4de7c89a4e28be07ec8326cc
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.32.0-alpha.b9027949a11ef01c4de7c89a4e28be07ec8326cc
