apiVersion: v2
appVersion: 1.32.0-alpha.527f8d6cb12ecb57ba2d9275306db5e4471d1a37
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- istiod
- istio-discovery
name: istiod
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.527f8d6cb12ecb57ba2d9275306db5e4471d1a37
