apiVersion: v2
appVersion: 1.31.0-alpha.fcc63ab39c7e90423e4bf8da215fb07d0ded7072
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

