apiVersion: v2
appVersion: 1.32.0-alpha.f199e14029c2831975a98c3032561742b6061d2c
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- istiod
- istio-discovery
name: istiod
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.f199e14029c2831975a98c3032561742b6061d2c
