apiVersion: v2
appVersion: 1.31.0-alpha.14f9ffc3f7955d0ad013bde88fdeee7ecdd3e35f
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

