apiVersion: v2
appVersion: 1.32.0-alpha.9c6b89c06753fcdcf741d10a5687e8c9d56a59d1
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.32.0-alpha.9c6b89c06753fcdcf741d10a5687e8c9d56a59d1
