#!/bin/bash

# Copyright Istio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates pkg/install/images.gen.go from deployment.annotations in a values file.
# This is decoupled from patch-values.sh so it works regardless of PATCH_HELM_VALUES.

set -euo pipefail

: "${YQ:=yq}"

VALUES_FILE="${1:?Usage: $0 <values_file_path>}"
SCRIPTPATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPTPATH}/.." && pwd)"
OUT="${ROOT}/pkg/install/images.gen.go"

declare -A IMAGES
declare -A SEEN_VERSIONS
VERSION_ORDER=()

while IFS= read -r line; do
  [[ "$line" =~ ^images\.v([0-9a-zA-Z._-]+)\.(istiod|proxy|cni|ztunnel):[[:space:]]*(.+)$ ]] || continue
  ver="${BASH_REMATCH[1]//_/.}"
  component="${BASH_REMATCH[2]}"
  value="${BASH_REMATCH[3]}"
  [[ "$value" =~ ^\$\{ ]] && continue
  IMAGES["${ver}.${component}"]="${value}"
  if [ -z "${SEEN_VERSIONS[$ver]+x}" ]; then
    SEEN_VERSIONS["${ver}"]=0
    VERSION_ORDER+=("${ver}")
  fi
  SEEN_VERSIONS["${ver}"]=$(( ${SEEN_VERSIONS["${ver}"]} + 1 ))
done < <(${YQ} '.deployment.annotations | to_entries[] | .key + ": " + .value' "${VALUES_FILE}")

cat common/scripts/copyright-banner-go.txt > "${OUT}"
cat >> "${OUT}" << 'GOHEADER'
// Code generated by hack/gen-images-go.sh. DO NOT EDIT.

package install

import "github.com/istio-ecosystem/sail-operator/pkg/config"

func init() {
	config.Config.ImageDigests = map[string]config.IstioImageConfig{
GOHEADER

for ver in "${VERSION_ORDER[@]}"; do
  [ "${SEEN_VERSIONS[$ver]}" -eq 4 ] || { echo "Warning: skipping version ${ver} (missing components)" >&2; continue; }
  cat >> "${OUT}" << GOENTRY
		"v${ver}": {
			IstiodImage:  "${IMAGES[$ver.istiod]}",
			ProxyImage:   "${IMAGES[$ver.proxy]}",
			CNIImage:     "${IMAGES[$ver.cni]}",
			ZTunnelImage: "${IMAGES[$ver.ztunnel]}",
		},
GOENTRY
done

cat >> "${OUT}" << 'GOFOOTER'
	}
}
GOFOOTER

echo "Generated ${OUT}"
