apiVersion: v2
appVersion: 1.31.0-alpha.046b063e480565e076966027fd8d2f4632d13787
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

