apiVersion: v2
appVersion: 1.30-alpha.a67661631b508b4c29e2507508fa5f0eeaba4e14
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

