apiVersion: v2
appVersion: 1.25-alpha.fd5c82be7c906785ce4d2f7611dcce17e842d33f
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.25-alpha.fd5c82be7c906785ce4d2f7611dcce17e842d33f
