apiVersion: v2
appVersion: 1.31.0-alpha.a217a27c4a0312c362abdee5b9e003870a251bba
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

