apiVersion: v2
appVersion: 1.31.0-alpha.bbcc281448b246e16e4502b93053de1a69dea559
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.bbcc281448b246e16e4502b93053de1a69dea559
