apiVersion: v2
appVersion: 1.31.0-alpha.c1848c8a6ebde02f90c421be08c359d32fcd66eb
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

