apiVersion: v2
appVersion: 1.31.0-alpha.734a0699dea61b141b8d26c07673c52c535e3860
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

