apiVersion: v2
appVersion: 1.31.0-alpha.c3a9d27567bc713c7ef38ef9f9a29f88415dfa25
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

