// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by hack/patch-values.sh. DO NOT EDIT.

package install

import "github.com/istio-ecosystem/sail-operator/pkg/config"

func init() {
	config.Config.ImageDigests = map[string]config.IstioImageConfig{
		"v1.30.2": {
			IstiodImage:  "registry.istio.io/release/pilot:1.30.2",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.30.2",
			CNIImage:     "registry.istio.io/release/install-cni:1.30.2",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.30.2",
		},
		"v1.30.1": {
			IstiodImage:  "registry.istio.io/release/pilot:1.30.1",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.30.1",
			CNIImage:     "registry.istio.io/release/install-cni:1.30.1",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.30.1",
		},
		"v1.30.0": {
			IstiodImage:  "registry.istio.io/release/pilot:1.30.0",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.30.0",
			CNIImage:     "registry.istio.io/release/install-cni:1.30.0",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.30.0",
		},
		"v1.29.5": {
			IstiodImage:  "registry.istio.io/release/pilot:1.29.5",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.29.5",
			CNIImage:     "registry.istio.io/release/install-cni:1.29.5",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.29.5",
		},
		"v1.29.4": {
			IstiodImage:  "registry.istio.io/release/pilot:1.29.4",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.29.4",
			CNIImage:     "registry.istio.io/release/install-cni:1.29.4",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.29.4",
		},
		"v1.29.3": {
			IstiodImage:  "registry.istio.io/release/pilot:1.29.3",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.29.3",
			CNIImage:     "registry.istio.io/release/install-cni:1.29.3",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.29.3",
		},
		"v1.29.2": {
			IstiodImage:  "registry.istio.io/release/pilot:1.29.2",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.29.2",
			CNIImage:     "registry.istio.io/release/install-cni:1.29.2",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.29.2",
		},
		"v1.29.1": {
			IstiodImage:  "registry.istio.io/release/pilot:1.29.1",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.29.1",
			CNIImage:     "registry.istio.io/release/install-cni:1.29.1",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.29.1",
		},
		"v1.29.0": {
			IstiodImage:  "registry.istio.io/release/pilot:1.29.0",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.29.0",
			CNIImage:     "registry.istio.io/release/install-cni:1.29.0",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.29.0",
		},
		"v1.28.9": {
			IstiodImage:  "registry.istio.io/release/pilot:1.28.9",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.28.9",
			CNIImage:     "registry.istio.io/release/install-cni:1.28.9",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.28.9",
		},
		"v1.28.8": {
			IstiodImage:  "registry.istio.io/release/pilot:1.28.8",
			ProxyImage:   "registry.istio.io/release/proxyv2:1.28.8",
			CNIImage:     "registry.istio.io/release/install-cni:1.28.8",
			ZTunnelImage: "registry.istio.io/release/ztunnel:1.28.8",
		},
		"v1.31.0-alpha.14f9ffc3": {
			IstiodImage:  "registry.istio.io/testing/pilot:1.31.0-alpha.14f9ffc3f7955d0ad013bde88fdeee7ecdd3e35f",
			ProxyImage:   "registry.istio.io/testing/proxyv2:1.31.0-alpha.14f9ffc3f7955d0ad013bde88fdeee7ecdd3e35f",
			CNIImage:     "registry.istio.io/testing/install-cni:1.31.0-alpha.14f9ffc3f7955d0ad013bde88fdeee7ecdd3e35f",
			ZTunnelImage: "registry.istio.io/testing/ztunnel:1.31.0-alpha.14f9ffc3f7955d0ad013bde88fdeee7ecdd3e35f",
		},
	}
}
