// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by hack/gen-images-go.sh. DO NOT EDIT.

package install

import "github.com/istio-ecosystem/sail-operator/pkg/config"

func init() {
	config.Config.ImageDigests = map[string]config.IstioImageConfig{
		"v1.30.3": {
			IstiodImage:  "build-harbor.alauda.cn/asm/pilot:1.30.3-asm-rc.4",
			ProxyImage:   "build-harbor.alauda.cn/asm/proxyv2:1.30.3-asm-rc.4",
			CNIImage:     "build-harbor.alauda.cn/asm/install-cni:1.30.3-asm-rc.4",
			ZTunnelImage: "build-harbor.alauda.cn/asm/ztunnel:1.30.3-asm-rc.4",
		},
		"v1.28.6": {
			IstiodImage:  "build-harbor.alauda.cn/asm/pilot:1.28.6-asm-r4",
			ProxyImage:   "build-harbor.alauda.cn/asm/proxyv2:1.28.6-asm-r4",
			CNIImage:     "build-harbor.alauda.cn/asm/install-cni:1.28.6-asm-r4",
			ZTunnelImage: "build-harbor.alauda.cn/asm/ztunnel:1.28.6-asm-r4",
		},
		"v1.28.3": {
			IstiodImage:  "build-harbor.alauda.cn/asm/pilot:1.28.3-asm-r3",
			ProxyImage:   "build-harbor.alauda.cn/asm/proxyv2:1.28.3-asm-r3",
			CNIImage:     "build-harbor.alauda.cn/asm/install-cni:1.28.3-asm-r3",
			ZTunnelImage: "build-harbor.alauda.cn/asm/ztunnel:1.28.3-asm-r3",
		},
		"v1.28.1": {
			IstiodImage:  "build-harbor.alauda.cn/asm/pilot:1.28.1-asm-r4",
			ProxyImage:   "build-harbor.alauda.cn/asm/proxyv2:1.28.1-asm-r4",
			CNIImage:     "build-harbor.alauda.cn/asm/install-cni:1.28.1-asm-r4",
			ZTunnelImage: "build-harbor.alauda.cn/asm/ztunnel:1.28.1-asm-r4",
		},
	}
}
