apiVersion: v2
appVersion: 1.25-alpha.329294ba9a7900f5e7a4e6c343e06f246c3627c3
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.25-alpha.329294ba9a7900f5e7a4e6c343e06f246c3627c3
