apiVersion: v2
appVersion: 1.32.0-alpha.102b69cd5a7ac0917bc2f6cb05b6217532145c81
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.102b69cd5a7ac0917bc2f6cb05b6217532145c81
