apiVersion: v2
appVersion: 1.30-alpha.f44b47959894b1f460d9e0cc301578ce77619bfc
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

