apiVersion: v2
appVersion: 1.30-alpha.98924b7b73f7c18d5c8ebba2112e7ea3e6344a65
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.30-alpha.98924b7b73f7c18d5c8ebba2112e7ea3e6344a65
