apiVersion: v2
appVersion: 1.30-alpha.ba49f7398a8542c3612788e9bd0371c079e44165
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.30-alpha.ba49f7398a8542c3612788e9bd0371c079e44165
