apiVersion: v2
appVersion: 1.31.0-alpha.3081a157e59d6b8b79df22df7f4129cfc89b1c68
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

