apiVersion: v2
appVersion: 1.31.0-alpha.0765bd223222b2dde110075eb105563787cdf6de
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

