apiVersion: v2
appVersion: 1.31.0-alpha.bd309b9694ffa3ff26ac0c322745bfee9e13ea2f
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

