// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Test code generated by AI. Reviewed and updated by the package author.
package analyze

import (
	"context"
	"testing"
	"time"

	v1 "github.com/istio-ecosystem/sail-operator/api/v1"
	"github.com/istio-ecosystem/sail-operator/pkg/config"
	"github.com/prometheus/client_golang/prometheus"
	model "github.com/prometheus/client_model/go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func createScheme(t *testing.T) *runtime.Scheme {
	t.Helper()
	scheme := runtime.NewScheme()
	if err := corev1.AddToScheme(scheme); err != nil {
		t.Fatalf("failed to add corev1 scheme: %v", err)
	}
	if err := v1.AddToScheme(scheme); err != nil {
		t.Fatalf("failed to add v1 scheme: %v", err)
	}
	return scheme
}

func getGaugeValue(t *testing.T, g prometheus.Gauge) float64 {
	var metric model.Metric
	if err := g.Write(&metric); err != nil {
		t.Errorf("failed to write metric: %v", err)
		return -1
	}
	if metric.Gauge == nil || metric.Gauge.Value == nil {
		t.Errorf("metric is not a gauge or has no value")
		return -1
	}
	return *metric.Gauge.Value
}

func TestListMetrics(t *testing.T) {
	metricsList := ListMetrics()
	if len(metricsList) != len(metricDescription) {
		t.Errorf("expected %d metrics, got %d", len(metricDescription), len(metricsList))
	}

	foundMap := make(map[string]bool)
	for _, m := range metricsList {
		foundMap[m.Name] = true
	}

	for _, expected := range metricDescription {
		if !foundMap[expected.Name] {
			t.Errorf("expected metric name %q to be in ListMetrics output", expected.Name)
		}
	}
}

func TestRecordMetrics(t *testing.T) {
	scheme := createScheme(t)

	// Prepare mock Kubernetes resources
	initObjects := []runtime.Object{
		// Istio resources
		&v1.Istio{
			ObjectMeta: metav1.ObjectMeta{Name: "istio-1"},
			Spec:       v1.IstioSpec{Version: "v1.30.0"},
		},
		&v1.Istio{
			ObjectMeta: metav1.ObjectMeta{Name: "istio-2"},
			Spec:       v1.IstioSpec{Version: "v1.31.0"},
		},
		&v1.Istio{
			ObjectMeta: metav1.ObjectMeta{Name: "istio-3"},
			Spec:       v1.IstioSpec{Version: "v1.31.0"},
		},

		// ZTunnel resources
		&v1.ZTunnel{
			ObjectMeta: metav1.ObjectMeta{Name: "ztunnel-1"},
			Spec:       v1.ZTunnelSpec{Version: "v1.30.0"},
		},

		// Pods with sidecar proxies
		&corev1.Pod{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "pod-with-sidecar",
				Namespace: "default",
				Labels:    map[string]string{"security.istio.io/tlsMode": "istio"},
			},
		},
		&corev1.Pod{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "pod-without-sidecar",
				Namespace: "default",
			},
		},

		// Sidecar namespaces
		&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name:   "sidecar-ns-1",
				Labels: map[string]string{"istio-injection": "enabled"},
			},
		},
		&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name:   "sidecar-ns-2",
				Labels: map[string]string{"istio.io/rev": "canary"},
			},
		},

		// Ambient namespaces
		&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name:   "ambient-ns-1",
				Labels: map[string]string{"istio.io/dataplane-mode": "ambient"},
			},
		},
		&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name:   "ambient-ns-2",
				Labels: map[string]string{"istio.io/use-waypoint": "waypoint"},
			},
		},
		&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name:   "ambient-ns-3",
				Labels: map[string]string{"istio.io/use-waypoint": "waypoint", "istio.io/ingress-use-waypoint": "ingress-waypoint"},
			},
		},
	}

	fakeClient := fake.NewClientBuilder().WithScheme(scheme).WithRuntimeObjects(initObjects...).Build()
	recorder := NewMetricsRecorder(1*time.Second, fakeClient, config.ReconcilerConfig{})

	ctx := context.Background()
	recorder.recordMetrics(ctx)

	// Assert GaugeVec metrics
	if val := getGaugeValue(t, IstioVersionTotal.WithLabelValues("v1.30.0")); val != 1 {
		t.Errorf("expected IstioVersionTotal for v1.30.0 to be 1, got %f", val)
	}
	if val := getGaugeValue(t, IstioVersionTotal.WithLabelValues("v1.31.0")); val != 2 {
		t.Errorf("expected IstioVersionTotal for v1.31.0 to be 2, got %f", val)
	}
	if val := getGaugeValue(t, ZTunnelVersionTotal.WithLabelValues("v1.30.0")); val != 1 {
		t.Errorf("expected ZTunnelVersionTotal for v1.30.0 to be 1, got %f", val)
	}

	// Assert Gauge metrics
	if val := getGaugeValue(t, SidecarProxyTotal); val != 1 {
		t.Errorf("expected SidecarProxyTotal to be 1, got %f", val)
	}
	if val := getGaugeValue(t, SidecarNamespaceTotal); val != 2 {
		t.Errorf("expected SidecarNamespaceTotal to be 2, got %f", val)
	}
	if val := getGaugeValue(t, AmbientNamespaceTotal); val != 3 {
		t.Errorf("expected AmbientNamespaceTotal to be 3, got %f", val)
	}
}

func TestMetricsRecorder_StartStop(t *testing.T) {
	scheme := createScheme(t)
	fakeClient := fake.NewClientBuilder().WithScheme(scheme).Build()

	recorder := NewMetricsRecorder(10*time.Millisecond, fakeClient, config.ReconcilerConfig{})

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	recorder.Start(ctx)

	// Allow the ticker to trigger at least once
	time.Sleep(30 * time.Millisecond)
}

func TestEnsureNamespaceLabel(t *testing.T) {
	scheme := createScheme(t)

	tests := []struct {
		name              string
		operatorNamespace string
		initialNamespace  *corev1.Namespace
		expectError       bool
	}{
		{
			name:              "successfully patch existing namespace without labels",
			operatorNamespace: "openshift-operators",
			initialNamespace: &corev1.Namespace{
				ObjectMeta: metav1.ObjectMeta{
					Name: "openshift-operators",
				},
			},
			expectError: false,
		},
		{
			name:              "successfully patch existing namespace with existing labels",
			operatorNamespace: "openshift-operators",
			initialNamespace: &corev1.Namespace{
				ObjectMeta: metav1.ObjectMeta{
					Name:   "openshift-operators",
					Labels: map[string]string{"other-label": "true"},
				},
			},
			expectError: false,
		},
		{
			name:              "returns error when namespace does not exist",
			operatorNamespace: "openshift-operators",
			initialNamespace:  nil,
			expectError:       true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var initObjs []client.Object
			if tt.initialNamespace != nil {
				initObjs = append(initObjs, tt.initialNamespace)
			}

			fakeClient := fake.NewClientBuilder().WithScheme(scheme).WithObjects(initObjs...).Build()
			recorder := NewMetricsRecorder(1*time.Second, fakeClient, config.ReconcilerConfig{
				OperatorNamespace: tt.operatorNamespace,
			})

			ctx := context.Background()
			err := recorder.EnsureNamespaceLabel(ctx)

			if (err != nil) != tt.expectError {
				t.Fatalf("EnsureNamespaceLabel() error = %v, expectError %v", err, tt.expectError)
			}

			if !tt.expectError {
				updatedNs := &corev1.Namespace{}
				err := fakeClient.Get(ctx, client.ObjectKey{Name: tt.operatorNamespace}, updatedNs)
				if err != nil {
					t.Fatalf("failed to get patched namespace: %v", err)
				}

				labelVal, exists := updatedNs.Labels["openshift.io/cluster-monitoring"]
				if !exists || labelVal != "true" {
					t.Errorf("expected label openshift.io/cluster-monitoring=true, got exists=%v, val=%s", exists, labelVal)
				}

				if tt.initialNamespace.Labels != nil && tt.initialNamespace.Labels["other-label"] != "" {
					if updatedNs.Labels["other-label"] != "true" {
						t.Errorf("expected existing labels to be preserved")
					}
				}
			}
		})
	}
}
