apiVersion: v2
appVersion: 1.33.0-alpha.aa3b3439c451f28ca3aba577af41ac1f096b7cfe
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

