apiVersion: v2
appVersion: 1.30-alpha.f4cad55d44c09e41270312d3fae05d45f86777db
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

