apiVersion: v2
appVersion: 1.32.0-alpha.102b69cd5a7ac0917bc2f6cb05b6217532145c81
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.32.0-alpha.102b69cd5a7ac0917bc2f6cb05b6217532145c81
