apiVersion: v2
appVersion: 1.31.0-alpha.1a74628e1d91505f62652d670618eb35f5c5fd41
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

