apiVersion: v2
appVersion: 1.30-alpha.c733733e7f2f87b26df12f191ab83c247f4dba06
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

