apiVersion: v2
appVersion: 1.32.0-alpha.1af1a2ca3910ec13302d2975099578c2e602e633
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.1af1a2ca3910ec13302d2975099578c2e602e633
