// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Test code generated by AI. Reviewed and updated by the package author.

package main

import (
	"bytes"
	"fmt"
	"io"
	"sort"
	"strings"
	"testing"
	"text/template"

	"github.com/istio-ecosystem/sail-operator/pkg/analyze"
)

const docTemplate = `# Sail Operator Metrics` + `## Sail Operator Custom Metrics List{{range .}}
### {{.Name}}
{{.Help}} Type: {{.Type}}.
{{end}}`

// generateMetricsDoc sorts metrics and renders the documentation template to w.
func generateMetricsDoc(w io.Writer, metrics []analyze.MetricDescription) error {
	// Sort metrics by Name in-place or on a copy
	sort.Slice(metrics, func(i, j int) bool {
		return metrics[i].Name < metrics[j].Name
	})

	tmpl, err := template.New("Sail Operator Metrics").Parse(docTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	if err := tmpl.Execute(w, metrics); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

func TestGenerateMetricsDoc(t *testing.T) {
	tests := []struct {
		name           string
		inputMetrics   []analyze.MetricDescription
		expectedSubstr []string
		unexpectedStr  string
	}{
		{
			name: "single metric rendering",
			inputMetrics: []analyze.MetricDescription{
				{
					Name: "sail_operator_reconcile_total",
					Help: "Total number of reconciliations.",
					Type: "Counter",
				},
			},
			expectedSubstr: []string{
				"### sail_operator_reconcile_total",
				"Total number of reconciliations. Type: Counter.",
			},
		},
		{
			name: "alphabetical sorting of metrics",
			inputMetrics: []analyze.MetricDescription{
				{
					Name: "istio_metric",
					Help: "Istio metric help",
					Type: "Gauge",
				},
				{
					Name: "ambient_metric",
					Help: "Ambient metric help",
					Type: "Counter",
				},
			},
			expectedSubstr: []string{
				"### ambient_metric\nAmbient metric help Type: Counter.\n\n### istio_metric\nIstio metric help Type: Gauge.",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			err := generateMetricsDoc(&buf, tt.inputMetrics)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			output := buf.String()

			for _, substr := range tt.expectedSubstr {
				if !strings.Contains(output, substr) {
					t.Errorf("expected output to contain %q, but got:\n%s", substr, output)
				}
			}
		})
	}
}
