apiVersion: v2
appVersion: 1.31.0-alpha.775ef498018596564d385ce030353c3bb5e73c63
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

