apiVersion: v2
appVersion: 1.31.0-alpha.75893e6febb046a86e84e408082d0cde2b402af5
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

