apiVersion: v2
appVersion: 1.32.0-alpha.4761bfe593472393839b4564840be2cc66d14de9
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

