apiVersion: v2
appVersion: 1.30-alpha.222ea3cc6c86b04d0e6285a9c5e62156e8569889
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

