apiVersion: v2
appVersion: 1.32.0-alpha.1af1a2ca3910ec13302d2975099578c2e602e633
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

