apiVersion: v2
appVersion: 1.31-alpha.dd5b67e1d1a026e56dabc6e715f00c1cb852c315
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

