apiVersion: v2
appVersion: 1.31.0-alpha.02e0457e424cc357149949f055bfa680058524bc
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.02e0457e424cc357149949f055bfa680058524bc
