apiVersion: v2
appVersion: 1.30-alpha.c524abf09e44ad28cae388a652310070f19f9ac6
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

