apiVersion: v2
appVersion: 1.30-alpha.fa0ac38c00f96785fadfa88858f5a2dd2a820c94
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

