apiVersion: v2
appVersion: 1.30-alpha.0577d34dff605bde472940e928f992e090888d5b
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

