apiVersion: v2
appVersion: 1.32.0-alpha.0258343f395afaf4767090a13979d21291853075
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

