apiVersion: v2
appVersion: 1.30-alpha.f48aa0995a564cb2abf434b8c51fd3cb17759544
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.30-alpha.f48aa0995a564cb2abf434b8c51fd3cb17759544
