apiVersion: v2
appVersion: 1.30-alpha.94111a069f1fa9de6a23eb785265551d078c77bb
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

