apiVersion: v2
appVersion: 1.32.0-alpha.8dbd7f98c429ed384de5158d700c86f94991fc72
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

