apiVersion: v2
appVersion: 1.30-alpha.632728800eb26d1767271d9f92618c29ac001b75
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

