apiVersion: v2
appVersion: 1.32.0-alpha.a95724d2e610ea9b59fc31f3b5638bf4efdb4e91
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

