apiVersion: v2
appVersion: 1.28-alpha.4b505ec0ef4a13f7d436277c4275d7fafc8ec965
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.28-alpha.4b505ec0ef4a13f7d436277c4275d7fafc8ec965
