apiVersion: v2
appVersion: 1.30-alpha.f44b47959894b1f460d9e0cc301578ce77619bfc
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- istiod
- istio-discovery
name: istiod
sources:
- https://github.com/istio/istio
version: 1.30-alpha.f44b47959894b1f460d9e0cc301578ce77619bfc
