apiVersion: v2
appVersion: 1.30-alpha.d9ada8aa419ebc88620a6087ae56383768a1eb2c
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.30-alpha.d9ada8aa419ebc88620a6087ae56383768a1eb2c
