apiVersion: v2
appVersion: 1.31.0-alpha.4245fde3de64c1c6c98e21dd7f763723ff1d8bb3
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

