apiVersion: v2
appVersion: 1.32.0-alpha.09d3eb4658967b1c3e49b8f3369f136a5e03fcac
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.09d3eb4658967b1c3e49b8f3369f136a5e03fcac
