apiVersion: v2
appVersion: 1.31.0-alpha.77bfdc743714c3565c181c9b1d842af4c77fa931
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

