apiVersion: v2
appVersion: 1.32.0-alpha.77cc135c123180ec55425157ce915f6382ad84e9
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

