apiVersion: v2
appVersion: 1.31.0-alpha.25f4803ee1e64fc2fcb95d07b1c0e3353594e9a9
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

