apiVersion: v2
appVersion: 1.31-alpha.046d9df336757b2a7c3ef75a11d372c5dff92ca9
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

