apiVersion: v2
appVersion: 1.31.0-alpha.1240c8642d78ca543cbad07932a38d29810820f7
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

