apiVersion: v2
appVersion: 1.30-alpha.3741e5f5ac98d3c10fdea36f1b083c19b8669c05
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

