apiVersion: v2
appVersion: 1.31-alpha.046d9df336757b2a7c3ef75a11d372c5dff92ca9
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.31-alpha.046d9df336757b2a7c3ef75a11d372c5dff92ca9
