apiVersion: v2
appVersion: 1.32.0-alpha.10863c4d008fa620273a0cd281407f92091ad12d
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- istiod
- istio-discovery
name: istiod
sources:
- https://github.com/istio/istio
version: 1.32.0-alpha.10863c4d008fa620273a0cd281407f92091ad12d
