apiVersion: v2
appVersion: 1.30-alpha.4b85e40f136994c65f70df6c11048e08f8817a5b
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.30-alpha.4b85e40f136994c65f70df6c11048e08f8817a5b
