apiVersion: v2
appVersion: 1.30-alpha.c733733e7f2f87b26df12f191ab83c247f4dba06
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.30-alpha.c733733e7f2f87b26df12f191ab83c247f4dba06
