apiVersion: v2
appVersion: 1.31.0-alpha.c16f17382ea2d3bec9225829c3f0acfa17d44d6b
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.31.0-alpha.c16f17382ea2d3bec9225829c3f0acfa17d44d6b
