apiVersion: v2
appVersion: 1.31.0-alpha.ddc812f7772e9c9a25a3a53d146b1ccb21d1ed27
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.31.0-alpha.ddc812f7772e9c9a25a3a53d146b1ccb21d1ed27
