apiVersion: v2
appVersion: 1.30-alpha.1334b393da45e5c200b0c792eedbb20e3b30d8f0
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

