annotations:
  org.opencontainers.image.ref.name: refs/tags/1.28.6-asm-r5
  org.opencontainers.image.revision: 0ba0e343c733d18bd8a354d9b7442221ccfb9a88
  org.opencontainers.image.source: https://github.com/alauda-mesh/istio
apiVersion: v2
appVersion: 1.28.6-asm-r5
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.28.6-asm-r5
